// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: openmeeting/admin/admin.proto

package admin

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UserLoginReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UserLoginReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserLoginReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UserLoginReqMultiError, or
// nil if none found.
func (m *UserLoginReq) ValidateAll() error {
	return m.validate(true)
}

func (m *UserLoginReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Account

	// no validation rules for Password

	if len(errors) > 0 {
		return UserLoginReqMultiError(errors)
	}

	return nil
}

// UserLoginReqMultiError is an error wrapping multiple validation errors
// returned by UserLoginReq.ValidateAll() if the designated constraints aren't met.
type UserLoginReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserLoginReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserLoginReqMultiError) AllErrors() []error { return m }

// UserLoginReqValidationError is the validation error returned by
// UserLoginReq.Validate if the designated constraints aren't met.
type UserLoginReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserLoginReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserLoginReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserLoginReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserLoginReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserLoginReqValidationError) ErrorName() string { return "UserLoginReqValidationError" }

// Error satisfies the builtin error interface
func (e UserLoginReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserLoginReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserLoginReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserLoginReqValidationError{}

// Validate checks the field values on UserLoginResp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UserLoginResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserLoginResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UserLoginRespMultiError, or
// nil if none found.
func (m *UserLoginResp) ValidateAll() error {
	return m.validate(true)
}

func (m *UserLoginResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Token

	// no validation rules for UserID

	if len(errors) > 0 {
		return UserLoginRespMultiError(errors)
	}

	return nil
}

// UserLoginRespMultiError is an error wrapping multiple validation errors
// returned by UserLoginResp.ValidateAll() if the designated constraints
// aren't met.
type UserLoginRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserLoginRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserLoginRespMultiError) AllErrors() []error { return m }

// UserLoginRespValidationError is the validation error returned by
// UserLoginResp.Validate if the designated constraints aren't met.
type UserLoginRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserLoginRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserLoginRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserLoginRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserLoginRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserLoginRespValidationError) ErrorName() string { return "UserLoginRespValidationError" }

// Error satisfies the builtin error interface
func (e UserLoginRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserLoginResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserLoginRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserLoginRespValidationError{}

// Validate checks the field values on UserRegisterReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UserRegisterReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserRegisterReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UserRegisterReqMultiError, or nil if none found.
func (m *UserRegisterReq) ValidateAll() error {
	return m.validate(true)
}

func (m *UserRegisterReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Nickname

	// no validation rules for Account

	// no validation rules for Password

	if len(errors) > 0 {
		return UserRegisterReqMultiError(errors)
	}

	return nil
}

// UserRegisterReqMultiError is an error wrapping multiple validation errors
// returned by UserRegisterReq.ValidateAll() if the designated constraints
// aren't met.
type UserRegisterReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserRegisterReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserRegisterReqMultiError) AllErrors() []error { return m }

// UserRegisterReqValidationError is the validation error returned by
// UserRegisterReq.Validate if the designated constraints aren't met.
type UserRegisterReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserRegisterReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserRegisterReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserRegisterReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserRegisterReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserRegisterReqValidationError) ErrorName() string { return "UserRegisterReqValidationError" }

// Error satisfies the builtin error interface
func (e UserRegisterReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserRegisterReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserRegisterReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserRegisterReqValidationError{}

// Validate checks the field values on UserRegisterResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UserRegisterResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserRegisterResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UserRegisterRespMultiError, or nil if none found.
func (m *UserRegisterResp) ValidateAll() error {
	return m.validate(true)
}

func (m *UserRegisterResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return UserRegisterRespMultiError(errors)
	}

	return nil
}

// UserRegisterRespMultiError is an error wrapping multiple validation errors
// returned by UserRegisterResp.ValidateAll() if the designated constraints
// aren't met.
type UserRegisterRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserRegisterRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserRegisterRespMultiError) AllErrors() []error { return m }

// UserRegisterRespValidationError is the validation error returned by
// UserRegisterResp.Validate if the designated constraints aren't met.
type UserRegisterRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserRegisterRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserRegisterRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserRegisterRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserRegisterRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserRegisterRespValidationError) ErrorName() string { return "UserRegisterRespValidationError" }

// Error satisfies the builtin error interface
func (e UserRegisterRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserRegisterResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserRegisterRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserRegisterRespValidationError{}
