// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: push/push.proto

package push

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on PushMsgReq with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PushMsgReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PushMsgReq with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PushMsgReqMultiError, or
// nil if none found.
func (m *PushMsgReq) ValidateAll() error {
	return m.validate(true)
}

func (m *PushMsgReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetMsgData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PushMsgReqValidationError{
					field:  "MsgData",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PushMsgReqValidationError{
					field:  "MsgData",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMsgData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PushMsgReqValidationError{
				field:  "MsgData",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for ConversationID

	if len(errors) > 0 {
		return PushMsgReqMultiError(errors)
	}

	return nil
}

// PushMsgReqMultiError is an error wrapping multiple validation errors
// returned by PushMsgReq.ValidateAll() if the designated constraints aren't met.
type PushMsgReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PushMsgReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PushMsgReqMultiError) AllErrors() []error { return m }

// PushMsgReqValidationError is the validation error returned by
// PushMsgReq.Validate if the designated constraints aren't met.
type PushMsgReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PushMsgReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PushMsgReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PushMsgReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PushMsgReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PushMsgReqValidationError) ErrorName() string { return "PushMsgReqValidationError" }

// Error satisfies the builtin error interface
func (e PushMsgReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPushMsgReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PushMsgReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PushMsgReqValidationError{}

// Validate checks the field values on PushMsgResp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PushMsgResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PushMsgResp with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PushMsgRespMultiError, or
// nil if none found.
func (m *PushMsgResp) ValidateAll() error {
	return m.validate(true)
}

func (m *PushMsgResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return PushMsgRespMultiError(errors)
	}

	return nil
}

// PushMsgRespMultiError is an error wrapping multiple validation errors
// returned by PushMsgResp.ValidateAll() if the designated constraints aren't met.
type PushMsgRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PushMsgRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PushMsgRespMultiError) AllErrors() []error { return m }

// PushMsgRespValidationError is the validation error returned by
// PushMsgResp.Validate if the designated constraints aren't met.
type PushMsgRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PushMsgRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PushMsgRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PushMsgRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PushMsgRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PushMsgRespValidationError) ErrorName() string { return "PushMsgRespValidationError" }

// Error satisfies the builtin error interface
func (e PushMsgRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPushMsgResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PushMsgRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PushMsgRespValidationError{}

// Validate checks the field values on DelUserPushTokenReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DelUserPushTokenReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DelUserPushTokenReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DelUserPushTokenReqMultiError, or nil if none found.
func (m *DelUserPushTokenReq) ValidateAll() error {
	return m.validate(true)
}

func (m *DelUserPushTokenReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserID

	// no validation rules for PlatformID

	if len(errors) > 0 {
		return DelUserPushTokenReqMultiError(errors)
	}

	return nil
}

// DelUserPushTokenReqMultiError is an error wrapping multiple validation
// errors returned by DelUserPushTokenReq.ValidateAll() if the designated
// constraints aren't met.
type DelUserPushTokenReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DelUserPushTokenReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DelUserPushTokenReqMultiError) AllErrors() []error { return m }

// DelUserPushTokenReqValidationError is the validation error returned by
// DelUserPushTokenReq.Validate if the designated constraints aren't met.
type DelUserPushTokenReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DelUserPushTokenReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DelUserPushTokenReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DelUserPushTokenReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DelUserPushTokenReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DelUserPushTokenReqValidationError) ErrorName() string {
	return "DelUserPushTokenReqValidationError"
}

// Error satisfies the builtin error interface
func (e DelUserPushTokenReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDelUserPushTokenReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DelUserPushTokenReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DelUserPushTokenReqValidationError{}

// Validate checks the field values on DelUserPushTokenResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DelUserPushTokenResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DelUserPushTokenResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DelUserPushTokenRespMultiError, or nil if none found.
func (m *DelUserPushTokenResp) ValidateAll() error {
	return m.validate(true)
}

func (m *DelUserPushTokenResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DelUserPushTokenRespMultiError(errors)
	}

	return nil
}

// DelUserPushTokenRespMultiError is an error wrapping multiple validation
// errors returned by DelUserPushTokenResp.ValidateAll() if the designated
// constraints aren't met.
type DelUserPushTokenRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DelUserPushTokenRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DelUserPushTokenRespMultiError) AllErrors() []error { return m }

// DelUserPushTokenRespValidationError is the validation error returned by
// DelUserPushTokenResp.Validate if the designated constraints aren't met.
type DelUserPushTokenRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DelUserPushTokenRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DelUserPushTokenRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DelUserPushTokenRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DelUserPushTokenRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DelUserPushTokenRespValidationError) ErrorName() string {
	return "DelUserPushTokenRespValidationError"
}

// Error satisfies the builtin error interface
func (e DelUserPushTokenRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDelUserPushTokenResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DelUserPushTokenRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DelUserPushTokenRespValidationError{}
